<?php

namespace Sherl\Sdk\Organization\Enum;

enum KYCDocumentRefusedReasonTypeEnum: string
{
    case DOCUMENT_UNREADABLE = 'DOCUMENT_UNREADABLE';
    case DOCUMENT_NOT_ACCEPTED = 'DOCUMENT_NOT_ACCEPTED';
    case DOCUMENT_HAS_EXPIRED = 'DOCUMENT_HAS_EXPIRED';
    case DOCUMENT_INCOMPLETE = 'DOCUMENT_INCOMPLETE';
    case DOCUMENT_MISSING = 'DOCUMENT_MISSING';
    case DOCUMENT_DO_NOT_MATCH_USER_DATA = 'DOCUMENT_DO_NOT_MATCH_USER_DATA';
    case DOCUMENT_DO_NOT_MATCH_ACCOUNT_DATA = 'DOCUMENT_DO_NOT_MATCH_ACCOUNT_DATA';
    case SPECIFIC_CASE = 'SPECIFIC_CASE';
    case DOCUMENT_FALSIFIED = 'DOCUMENT_FALSIFIED';
    case UNDERAGE_PERSON = 'UNDERAGE_PERSON';
}
