<?php

namespace Sherl\Sdk\Calendar\Enum;

enum CalendarConfig: string
{
    case MAX_DISTANCE_FROM_OWNER = 'CALENDAR_MAX_DISTANCE_FROM_OWNER';
    case MAX_DISTANCE_BETWEEN_EVENTS = 'CALENDAR_MAX_DISTANCE_BETWEEN_EVENTS';
    case LOCATION_RESTRICTION_TYPE = 'CALENDAR_LOCATION_RESTRICTION_TYPE';
    case ALLOWED_LOCALITIES = 'CALENDAR_ALLOWED_LOCALITIES';
}
